ARG BUILDER

# 빌드용 도커 이미지
FROM ${BUILDER} AS builder

ARG MAIN_PATH

# 소스복사
WORKDIR /build
COPY . .

# 빌드
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-s' -o main ${MAIN_PATH}

FROM scratch
ARG EXPOSE
EXPOSE ${EXPOSE}
COPY --from=builder /build/main /main

# ca-certificates 설정 (https 통신)
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/main"]
